### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by valentin-shipilov** [rundef/node-testrail-api#19]
There is a error in the code: index.js line 90: `callback(err.message || err)`
but this code branch executed when `typeof callback !== 'function'`

**Comment by valentin-shipilov** [comment]
I get this error on index.php?/api/v2/get_user_by_email&email=foo@bar.baz
Test Rail returns 404 with empty body when there is no user with such email

**Comment by cenfun** [comment]
same issue here: 
node_modules/testrail-api/index.js:90
            return callback(err.message || err);
                   ^
TypeError: callback is not a function

**Comment by vladimirparlik** [comment]
Same issue here: TypeError: callback is not a function.

Will this be fixed soon?

**Comment by tvial-tagheuer** [comment]
Same error here.
Strange to call `callback` when  it's not a function (there's already a `if` for that).
@rundef what do you suggest in order for us to provide a PR.
What is the expected behaviour?
Thanks.

**Comment by rundef** [comment]
Really sorry for the long wait guys ...
@tvial-tagheuer Can you let me know if it's working with version 1.3.6 ? Thanks

**Comment by tvial-tagheuer** [comment]
Hi @rundef, I tried but does not solve the issue.
Message is :

`Unhandled rejection (<{"message":"Unexpected token < in JSON...>, no stack trace)`

`err.message` value is:
`Unexpected token < in JSON at position 0`

The body being an HTML page with error 400.

**Comment by tvial-tagheuer** [comment]
On a side note, you added `rejectUnauthorized: false` but you already had it.

https://github.com/rundef/node-testrail-api/blob/e09e446276c5ace050234b82fc60006dde6e6ee1/index.js#L47-L55
